"""Add detection metadata and audit logs

Revision ID: 073d8145270a
Revises: 20260921_0003
Create Date: 2026-09-24 19:02:15.592129
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '073d8145270a'
down_revision: Union[str, None] = '20260921_0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    with op.batch_alter_table('detections') as batch_op:
        batch_op.add_column(sa.Column('image_content_type', sa.String(length=50), nullable=False, server_default='image/jpeg'))
        batch_op.add_column(sa.Column('image_size_bytes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requires_confirmation', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('confirmed_plate', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('confirmed_by_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_detections_confirmed_by_id_users', 'users', ['confirmed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    with op.batch_alter_table('detections') as batch_op:
        batch_op.drop_constraint('fk_detections_confirmed_by_id_users', type_='foreignkey')
        batch_op.drop_column('confirmed_by_id')
        batch_op.drop_column('confirmed_plate')
        batch_op.drop_column('is_confirmed')
        batch_op.drop_column('requires_confirmation')
        batch_op.drop_column('image_size_bytes')
        batch_op.drop_column('image_content_type')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
