"""add snapshot columns to parking transaction

Revision ID: 7f694ec0b142
Revises: 20261006_0006
Create Date: 2026-10-07 22:05:16.203774
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "7f694ec0b142"
down_revision: str | None = "20261006_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("parking_transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("operator_snapshot_name", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(sa.Column("lane_snapshot_name", sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column("lane_snapshot_direction", sa.String(length=20), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("parking_transactions", schema=None) as batch_op:
        batch_op.drop_column("lane_snapshot_direction")
        batch_op.drop_column("lane_snapshot_name")
        batch_op.drop_column("operator_snapshot_name")

    # ### end Alembic commands ###
