"""Create detection tables

Revision ID: aa276e942822
Revises: 20260918_0002_create_lane_tables
Create Date: 2026-09-18 22:28:25.334341
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa276e942822'
down_revision: Union[str, None] = '20260918_0002_create_lane_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('lane_id', sa.String(length=50), nullable=False),
    sa.Column('image_key', sa.String(length=255), nullable=False, comment='Storage key do ImageStorage trả về'),
    sa.Column('raw_plate', sa.String(length=50), nullable=True),
    sa.Column('normalized_plate', sa.String(length=50), nullable=True),
    sa.Column('bbox_x1', sa.Integer(), nullable=True),
    sa.Column('bbox_y1', sa.Integer(), nullable=True),
    sa.Column('bbox_x2', sa.Integer(), nullable=True),
    sa.Column('bbox_y2', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detections_image_key'), ['image_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_lane_id'), ['lane_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_normalized_plate'), ['normalized_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_raw_plate'), ['raw_plate'], unique=False)

    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.alter_column('direction',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('IN', 'OUT', name='lanedirection'),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_lanes_direction'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lanes_direction'), ['direction'], unique=False)
        batch_op.alter_column('direction',
               existing_type=sa.Enum('IN', 'OUT', name='lanedirection'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detections_raw_plate'))
        batch_op.drop_index(batch_op.f('ix_detections_normalized_plate'))
        batch_op.drop_index(batch_op.f('ix_detections_lane_id'))
        batch_op.drop_index(batch_op.f('ix_detections_image_key'))

    op.drop_table('detections')
    # ### end Alembic commands ###
